// <auto-generated />
using ApiCine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiCine.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322023719_AddTables")]
    partial class AddTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("ApiCine.Features.Genero.GeneroEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Genero", (string)null);
                });

            modelBuilder.Entity("ApiCine.Features.Pelicula.PeliculaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Duracion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Pelicula", (string)null);
                });

            modelBuilder.Entity("ApiCine.Features.Relaciones.PeliculaGenero.PeliculaGeneroEntity", b =>
                {
                    b.Property<long>("PeliculaId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GeneroId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PeliculaId", "GeneroId");

                    b.HasIndex("GeneroId");

                    b.ToTable("Pelicula_Genero", (string)null);
                });

            modelBuilder.Entity("ApiCine.Features.Relaciones.PeliculaGenero.PeliculaGeneroEntity", b =>
                {
                    b.HasOne("ApiCine.Features.Genero.GeneroEntity", "Genero")
                        .WithMany("PeliculaGeneros")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiCine.Features.Pelicula.PeliculaEntity", "Pelicula")
                        .WithMany("PeliculaGeneros")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("ApiCine.Features.Genero.GeneroEntity", b =>
                {
                    b.Navigation("PeliculaGeneros");
                });

            modelBuilder.Entity("ApiCine.Features.Pelicula.PeliculaEntity", b =>
                {
                    b.Navigation("PeliculaGeneros");
                });
#pragma warning restore 612, 618
        }
    }
}
