// <auto-generated />
using System;
using ApiCine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiCine.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322064647_addTablesFuncion")]
    partial class addTablesFuncion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("ApiCine.Features.Funcion.FuncionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<long>("PeliculaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<long>("SalaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeliculaId");

                    b.HasIndex("SalaId");

                    b.HasIndex("FechaHora", "SalaId")
                        .IsUnique()
                        .HasDatabaseName("IX_Funcion_FechaHora_SalaId");

                    b.ToTable("funcion", (string)null);
                });

            modelBuilder.Entity("ApiCine.Features.Genero.GeneroEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Genero", (string)null);
                });

            modelBuilder.Entity("ApiCine.Features.Pelicula.PeliculaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Duracion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Pelicula", (string)null);
                });

            modelBuilder.Entity("ApiCine.Features.Relaciones.PeliculaGenero.PeliculaGeneroEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("GeneroId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PeliculaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GeneroId");

                    b.HasIndex("PeliculaId", "GeneroId")
                        .IsUnique()
                        .HasDatabaseName("IX_PeliculaGenero_PeliculaId_GeneroId");

                    b.ToTable("Pelicula_Genero", (string)null);
                });

            modelBuilder.Entity("ApiCine.Features.Sala.SalaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SalaEntity");
                });

            modelBuilder.Entity("ApiCine.Features.Funcion.FuncionEntity", b =>
                {
                    b.HasOne("ApiCine.Features.Pelicula.PeliculaEntity", "Pelicula")
                        .WithMany("Funciones")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiCine.Features.Sala.SalaEntity", "Sala")
                        .WithMany("Funciones")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pelicula");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("ApiCine.Features.Relaciones.PeliculaGenero.PeliculaGeneroEntity", b =>
                {
                    b.HasOne("ApiCine.Features.Genero.GeneroEntity", "Genero")
                        .WithMany("PeliculaGeneros")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiCine.Features.Pelicula.PeliculaEntity", "Pelicula")
                        .WithMany("PeliculaGeneros")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("ApiCine.Features.Genero.GeneroEntity", b =>
                {
                    b.Navigation("PeliculaGeneros");
                });

            modelBuilder.Entity("ApiCine.Features.Pelicula.PeliculaEntity", b =>
                {
                    b.Navigation("Funciones");

                    b.Navigation("PeliculaGeneros");
                });

            modelBuilder.Entity("ApiCine.Features.Sala.SalaEntity", b =>
                {
                    b.Navigation("Funciones");
                });
#pragma warning restore 612, 618
        }
    }
}
