// <auto-generated />
using System;
using ApiCine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiCine.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("ApiCine.Features.Asiento.AsientoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fila")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SalaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SalaId");

                    b.ToTable("Asiento");
                });

            modelBuilder.Entity("ApiCine.Features.Funcion.FuncionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<long>("PeliculaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<long>("SalaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeliculaId");

                    b.HasIndex("SalaId");

                    b.HasIndex("FechaHora", "SalaId")
                        .IsUnique()
                        .HasDatabaseName("IX_Funcion_FechaHora_SalaId");

                    b.ToTable("funcion", (string)null);
                });

            modelBuilder.Entity("ApiCine.Features.Genero.GeneroEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Genero", (string)null);
                });

            modelBuilder.Entity("ApiCine.Features.Pelicula.PeliculaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Duracion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Pelicula", (string)null);
                });

            modelBuilder.Entity("ApiCine.Features.Relaciones.PeliculaGenero.PeliculaGeneroEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("GeneroId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PeliculaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GeneroId");

                    b.HasIndex("PeliculaId", "GeneroId")
                        .IsUnique()
                        .HasDatabaseName("IX_PeliculaGenero_PeliculaId_GeneroId");

                    b.ToTable("Pelicula_Genero", (string)null);
                });

            modelBuilder.Entity("ApiCine.Features.Relaciones.ReservaAsientos.ReservaAsientoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AsientoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FuncionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReservaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AsientoId");

                    b.HasIndex("ReservaId");

                    b.HasIndex("FuncionId", "AsientoId")
                        .IsUnique()
                        .HasDatabaseName("IX_ReservaAsiento_FuncionId_AsientoId");

                    b.ToTable("Reserva_asiento", (string)null);
                });

            modelBuilder.Entity("ApiCine.Features.Reserva.ReservaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<long>("FuncionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FuncionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reserva", (string)null);
                });

            modelBuilder.Entity("ApiCine.Features.Sala.SalaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadColumnas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadFilas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cod")
                        .IsUnique()
                        .HasDatabaseName("IX_Sala_Cod");

                    b.ToTable("Sala", (string)null);
                });

            modelBuilder.Entity("ApiCine.Features.Usuario.UsuarioEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("ApiCine.Features.Asiento.AsientoEntity", b =>
                {
                    b.HasOne("ApiCine.Features.Sala.SalaEntity", "Sala")
                        .WithMany("Asientos")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("ApiCine.Features.Funcion.FuncionEntity", b =>
                {
                    b.HasOne("ApiCine.Features.Pelicula.PeliculaEntity", "Pelicula")
                        .WithMany("Funciones")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiCine.Features.Sala.SalaEntity", "Sala")
                        .WithMany("Funciones")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pelicula");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("ApiCine.Features.Relaciones.PeliculaGenero.PeliculaGeneroEntity", b =>
                {
                    b.HasOne("ApiCine.Features.Genero.GeneroEntity", "Genero")
                        .WithMany("PeliculaGeneros")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiCine.Features.Pelicula.PeliculaEntity", "Pelicula")
                        .WithMany("PeliculaGeneros")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("ApiCine.Features.Relaciones.ReservaAsientos.ReservaAsientoEntity", b =>
                {
                    b.HasOne("ApiCine.Features.Asiento.AsientoEntity", "Asiento")
                        .WithMany("reservaAsientos")
                        .HasForeignKey("AsientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiCine.Features.Funcion.FuncionEntity", "Funcion")
                        .WithMany("ReservaAsientos")
                        .HasForeignKey("FuncionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiCine.Features.Reserva.ReservaEntity", "Reserva")
                        .WithMany("reservaAsientos")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asiento");

                    b.Navigation("Funcion");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("ApiCine.Features.Reserva.ReservaEntity", b =>
                {
                    b.HasOne("ApiCine.Features.Funcion.FuncionEntity", "Funcion")
                        .WithMany("Reservas")
                        .HasForeignKey("FuncionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiCine.Features.Usuario.UsuarioEntity", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiCine.Features.Asiento.AsientoEntity", b =>
                {
                    b.Navigation("reservaAsientos");
                });

            modelBuilder.Entity("ApiCine.Features.Funcion.FuncionEntity", b =>
                {
                    b.Navigation("ReservaAsientos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ApiCine.Features.Genero.GeneroEntity", b =>
                {
                    b.Navigation("PeliculaGeneros");
                });

            modelBuilder.Entity("ApiCine.Features.Pelicula.PeliculaEntity", b =>
                {
                    b.Navigation("Funciones");

                    b.Navigation("PeliculaGeneros");
                });

            modelBuilder.Entity("ApiCine.Features.Reserva.ReservaEntity", b =>
                {
                    b.Navigation("reservaAsientos");
                });

            modelBuilder.Entity("ApiCine.Features.Sala.SalaEntity", b =>
                {
                    b.Navigation("Asientos");

                    b.Navigation("Funciones");
                });

            modelBuilder.Entity("ApiCine.Features.Usuario.UsuarioEntity", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
